//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipees
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe_ingredient
    {
        public int recipe_id { get; set; }
        public int ingredient_id { get; set; }
        public int nummber_ingredient { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
