//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        public int Id { get; set; }
        public string fk_ingredients { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
    
        public virtual recipe recipe { get; set; }
    }
}
