//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipes
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe()
        {
            this.ingredients1 = new HashSet<ingredient>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int ingredients { get; set; }
        public Nullable<bool> done { get; set; }
        public Nullable<bool> favourites { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredient> ingredients1 { get; set; }
    }
}
